title: Dockerfiles
logo: /favicon.png
description: A collection of dockerfiles for NVIDIA DGX-230 machine.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-titles-from-headings
  - jekyll-seo-tag
markdown: kramdown
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
